name: Deploy Datasets

on:
  workflow_run:
    workflows:
       - Deploy ADF LinkedService
    types:
       - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Azure CLI
        uses: azure/CLI@v1
        with:
          azcliversion: '2.30.0'  # Correct input for specifying Azure CLI version
          inlineScript: |
            az --version  # Example inline script to verify Azure CLI setup

      - name: Install jq
        run: sudo apt-get install jq

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SPN_CREDENTIALS }}  # Make sure to store your Azure credentials as secrets

      - name: Read pipeline Dataset JSON files and deploy
        run: |
          # Ensure the correct path to the JSON files
          dataset1=$(cat ./datasets/TestDataset.json)
          dataset2=$(cat ./datasets/TestDataset2.json)
          dataset3=$(cat ./datasets/komatsu_test.json)

          # Construct a JSON array with the dataset contents
          datasets=$(jq -n \
            --arg dataset1 "$dataset1" \
            --arg dataset2 "$dataset2" \
            --arg dataset3 "$dataset3" \
            '[
              {
                "name": "TestDataset",
                "definition": $dataset1 | fromjson
              },
              {
                "name": "TestDataset2",
                "definition": $dataset2 | fromjson
              },
              {
                "name": "komatsu_test",
                "definition": $dataset3 | fromjson
              }
            ]')

          # Deploy using Bicep (or ARM template)
          az deployment group create \
            --resource-group "komatsu" \
            --template-file ./bicep/modules/dataset.bicep \
            --parameters dataFactoryName=ADF-components \
            --parameters datasets="$datasets"