name: Deploy ADF LinkedService

on:
  # workflow_call:
  #   inputs:
  #     branch:

  #       required: true
  #       type: string
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Azure
      uses: azure/login@v2
      with:
        creds: >
              {
                "clientId":"${{ secrets.AZURE_CLIENT_ID_D_APIM }}",
                "clientSecret":"${{ secrets.AZURE_CLIENT_SECRET_D_APIM }}",
                "subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID_D_APIM }}",
                "tenantId":"${{ secrets.AZURE_TENANT_ID_D_APIM }}"
              }
        enable-AzPSSession: true

    - name: Validate Bicep Template
      run: |
        az deployment group validate \
            --resource-group komatsu \
            --template-file ./bicep/main.bicep \
            --parameters @./bicep/parameters.json

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Azure CLI
      uses: azure/CLI@v1
      with:
        azcliversion: '2.30.0'
        inlineScript: |
          az --version

    - name: Install jq
      run: sudo apt-get install jq

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.SPN_CREDENTIALS }}

    - name: Read linkedService JSON files and deploy
      run: |
        linkedService1=$(cat ./linkedService/TestLinkedService.json)
        linkedService2=$(cat ./linkedService/StorageTable.json)

        linkedServices=$(jq -n \
          --arg linkedService1 "$linkedService1" \
          --arg linkedService2 "$linkedService2" \
          '[
            {
              "name": "NewBlobStorage",
              "definition": $linkedService1 | fromjson
            },
            {
              "name": "NewStorageTable",
              "definition": $linkedService2 | fromjson
            }
          ]')

        az deployment group create \
          --resource-group "komatsu" \
          --template-file ./bicep/modules/linkedservice.bicep \
          --parameters dataFactoryName=ADF-components \
          --parameters linkedServices="$linkedServices"
