name: Deploy ADF Components Sequentially

on:
  push:
    branches:
      - main
 
     
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Azure
      uses: azure/login@v2
      with:
        creds: >
              {
                "clientId":"${{ secrets.AZURE_CLIENT_ID_D_APIM }}",
                "clientSecret":"${{ secrets.AZURE_CLIENT_SECRET_D_APIM }}",
                "subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID_D_APIM }}",
                "tenantId":"${{ secrets.AZURE_TENANT_ID_D_APIM }}"
              }
        enable-AzPSSession: true

  # deploy-LinkedService:
  #   needs: build
  #   uses: ./.github/workflows/LinkedService.yml
  #   with: 
  #     branch: souvikADFChanges
    

  # deploy-DataSets:
  #   needs: deploy-LinkedService
  #   uses: ./.github/workflows/DataSets.yml
  #   with: 
  #     branch: souvikADFChanges
    
    
  # deploy-Pipeline:
  #   needs: deploy-DataSets
  #   uses: ./.github/workflows/Pipeline.yml
  #   with: 
  #     branch: souvikADFChanges
    
  # deploy-Trigger:
    
  #   uses: ./.github/workflows/Trigger.yml
  #   with: 
  #     branch: souvikADFChanges
    
