name: Deploy ADF Components Sequentially

on:
  push:
    branches:
      - souvikADFChanges
 
     
jobs:

  deploy-LinkedService:
    uses: ./.github/workflows/LinkedService.yml
    with: 
      branch: souvikADFChanges
    

  deploy-DataSets:
    needs: deploy-LinkedService
    uses: ./.github/workflows/DataSets.yml
    with: 
      branch: souvikADFChanges
    
    
  deploy-Pipeline:
    needs: deploy-DataSets
    uses: ./.github/workflows/Pipeline.yml
    with: 
      branch: souvikADFChanges
    
  deploy-Trigger:
    
    uses: ./.github/workflows/Trigger.yml
    with: 
      branch: souvikADFChanges
    
