name: Deploy ADF Components Sequentially
 
on:
  push:
    branches:
      - souvikADFChanges  # Trigger workflow on push to the main branch
 
jobs:
  deploy-LinkedService:
    name: Deploy LinkedService.yml
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Azure CLI
        uses: azure/CLI@v1
        with:
          azcliversion: '2.30.0'  # Correct input for specifying Azure CLI version
          inlineScript: |
            az --version  # Example inline script to verify Azure CLI setup

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_SPN_CREDENTIAL }}  # Make sure to store your Azure credentials as secrets
      
      - name: Validate LinkedService.yml
        run: |
            yq eval -o=json ./.github/workflows/ADFcomponents/LinkedService.yml > ./.github/workflows/ADFcomponents/LinkedService.json
            az deployment group validate \
            --resource-group "komatsu" \
            --template-file ./.github/workflows/ADFcomponents/LinkedService.json

      - name: Deploy LinkedService.yml
        run: |
            yq eval -o=json ./.github/workflows/ADFcomponents/LinkedService.yml > ./.github/workflows/ADFcomponents/LinkedService.json
            az deployment group create \
            --resource-group "komatsu" \
            --template-file ./.github/workflows/ADFcomponents/LinkedService.json
 
  deploy-DataSets:
    name: Deploy DataSets.yml
    runs-on: ubuntu-latest
    needs: deploy-LinkedService
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
 
      - name: Deploy DataSets.yml
        run: |
          echo "Deploying DataSets.yml"
          az deployment group create 
          --resource-group "komatsu" \
          --template-file ./.github/workflows/ADFcomponents/DataSets.yml
 
  deploy-Pipeline:
    name: Deploy Pipeline.yml
    runs-on: ubuntu-latest
    needs: deploy-DataSets
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
 
      - name: Deploy Pipeline.yml
        run: |
          echo "Deploying Pipeline.yml"
          az deployment group create \
          --resource-group "komatsu" \
          --template-file ./.github/workflows/ADFcomponents/Pipeline.yml

  deploy-Trigger:
    name: Deploy Trigger.yml
    runs-on: ubuntu-latest
    needs: deploy-Pipeline
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
 
      - name: Deploy Trigger.yml
        run: |
          echo "Deploying Trigger.yml"
          az deployment group create \
          --resource-group "komatsu" \
          --template-file ./.github/workflows/ADFcomponents/Trigger.yml