name: Deploy ADF Components Sequentially
 
on:
  push:
    branches:
      - main  # Trigger workflow on push to the main branch
 
jobs:
  deploy-LinkedService:
    name: Deploy LinkedService.yml
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
 
      - name: Deploy LinkedService.yml
        run: |
            az deployment group create \
            --resource-group "komatsu" \
            --template-file ./.github/workflows/ADFcomponents/LinkedService.yml
 
  deploy-DataSets:
    name: Deploy DataSets.yml
    runs-on: ubuntu-latest
    needs: deploy-LinkedService
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
 
      - name: Deploy DataSets.yml
        run: |
          echo "Deploying DataSets.yml"
          az deployment group create 
          --resource-group "komatsu" \
          --template-file ./.github/workflows/ADFcomponents/DataSets.yml
 
  deploy-Pipeline:
    name: Deploy Pipeline.yml
    runs-on: ubuntu-latest
    needs: deploy-DataSets
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
 
      - name: Deploy Pipeline.yml
        run: |
          echo "Deploying Pipeline.yml"
          az deployment group create \
          --resource-group "komatsu" \
          --template-file ./.github/workflows/ADFcomponents/Pipeline.yml

  deploy-Trigger:
    name: Deploy Trigger.yml
    runs-on: ubuntu-latest
    needs: deploy-Pipeline
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
 
      - name: Deploy Trigger.yml
        run: |
          echo "Deploying Trigger.yml"
          az deployment group create \
          --resource-group "komatsu" \
          --template-file ./.github/workflows/ADFcomponents/Trigger.yml