name: Deploy ADF Components Sequentially

on:
  push:
    branches:
      - souvikADFChanges
 
     
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Azure CLI
      uses: azure/CLI@v2
      with:
        azcliversion: '2.30.0'
        inlineScript: |
          az --version

    - name: Install jq
      run: sudo apt-get install jq

    - name: Login to Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.SPN_CREDENTIALS }}

    - name: Validate Bicep Template
      run: |
        az deployment group validate \
            --resource-group komatsu \
            --template-file ./bicep/main.bicep \
            --parameters @./bicep/parameters.json

  deploy-LinkedService:
    needs: build
    uses: ./.github/workflows/LinkedService.yml
    with: 
      branch: souvikADFChanges
    

  deploy-DataSets:
    needs: deploy-LinkedService
    uses: ./.github/workflows/DataSets.yml
    with: 
      branch: souvikADFChanges
    
    
  deploy-Pipeline:
    needs: deploy-DataSets
    uses: ./.github/workflows/Pipeline.yml
    with: 
      branch: souvikADFChanges
    
  deploy-Trigger:
    
    uses: ./.github/workflows/Trigger.yml
    with: 
      branch: souvikADFChanges
    
