name: Deploy ADF Components Sequentially

on:
  push:
    branches:
      - souvikADFChanges
 
     
jobs:
  deploy-LinkedService:
    uses: ./.github/workflows/LinkedService.yml
    with: 
      branch: souvikADFChanges
    

  deploy-DataSets:
    uses: ./.github/workflows/DataSets.yml
    with: 
      branch: souvikADFChanges
    needs: deploy-LinkedService
    
  deploy-Pipeline:
    uses: ./.github/workflows/Pipeline.yml
    with: 
      branch: souvikADFChanges
    needs: deploy-DataSets

  deploy-Trigger:
    uses: ./.github/workflows/Trigger.yml
    with: 
      branch: souvikADFChanges
    needs: deploy-Pipeline
