name: Deploy YAML Files Sequentially
 
on:
  push:
    branches:
      - souvikADFChanges  # Trigger on push to main branch
 
jobs:
  deploy:
    runs-on: ubuntu-latest
 
    steps:
      # Checkout your code
      - name: Checkout code
        uses: actions/checkout@v3
 
      # Deploy file1.yml
      - name: Deploy LinkedService.yml
        run: |
          echo "Deploying LinkedService.yml"
          az deployment group create \
            --resource-group "komatsu" \
            --template-file ./.github/workflows/ADFcomponents/LinkedService.yml
 
      # Deploy file2.yml
      - name: Deploy DataSets.yml
        run: |
          echo "Deploying DataSets.yml"
          az deployment group create 
          --resource-group "komatsu" \
          --template-file ./.github/workflows/ADFcomponents/DataSets.yml
 
      # Deploy file3.yml
      - name: Deploy Pipeline.yml
        run: |
          echo "Deploying Pipeline.yml"
          az deployment group create \
          --resource-group "komatsu" \
          --template-file ./.github/workflows/ADFcomponents/Pipeline.yml
 
      # Deploy file4.yml
      - name: Deploy Trigger.yml
        run: |
          echo "Deploying Trigger.yml"
          az deployment group create \
          --resource-group "komatsu" \
          --template-file ./.github/workflows/ADFcomponents/Trigger.yml