name: Deploy ADF Trigger

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Azure CLI
      uses: azure/CLI@v1
      with:
        azcliversion: '2.30.0'  # Correct input for specifying Azure CLI version
        inlineScript: |
          az --version  # Example inline script to verify Azure CLI setup

    - name: Install jq
      run: sudo apt-get install jq

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.SPN_CREDENTIALS }}

    - name: Validate Bicep Template
      run: |
        az deployment group validate \
            --resource-group komatsu \
            --template-file ./bicep/main.bicep \
            --parameters @./bicep/parameters.json

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Azure CLI
      uses: azure/CLI@v1
      with:
        azcliversion: '2.30.0'  # Correct input for specifying Azure CLI version
        inlineScript: |
          az --version  # Example inline script to verify Azure CLI setup

    - name: Install jq
      run: sudo apt-get install jq

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_SPN_CREDENTIAL }}  # Make sure to store your Azure credentials as secrets

    - name: Read Trigger JSON files and deploy
      run: |
          # Ensure the correct path to the JSON files
          TestTrigger1=$(cat ./trigger/TestTrigger.json)
          TestTrigger2=$(cat ./trigger/24hourtrigger.json)

          # Construct a JSON array with the Trigger contents
          TestTrigger=$(jq -n \
            --arg TestTrigger1 "$TestTrigger1" \
            --arg TestTrigger2 "$TestTrigger2" \
            '[
              {
                "name": "BicepTrigger",
                "definition": $TestTrigger1 | fromjson
              },
              {
                "name": "24HourTrigger",
                "definition": $TestTrigger2 | fromjson
              }
            ]')

          # Deploy using Bicep (or ARM template)
          az deployment group create \
            --resource-group "komatsu" \
            --template-file ./bicep/modules/trigger.bicep \
            --parameters dataFactoryName=ADF-components \
            --parameters triggers="$TestTrigger"